# A simple command to stop the motors in
# case of problem

# Stop Constants
uint8 STOP_SOFT=1
uint8 STOP_HARD=2
uint8 STOP_HIZ=3

# Specify specific motors to stop
uint8[] motor_indice
uint8 stop_type

---
#response

float64[] est_time_to_stop
uint8[]   stop_type
