# Quick hack makefile to compile test utility

l6470_make : commands.cpp comms.cpp config.cpp motor.cpp multidriver.cpp support.cpp types.cpp l640_test.cpp
	g++ -std=c++11 -Wall -Werror commands.cpp comms.cpp config.cpp motor.cpp multidriver.cpp support.cpp types.cpp l640_test.cpp -o l640_test -lmraa
