# Quick hack makefile to compile test utility

l6470_make : commands.cpp config.cpp driver.cpp support.cpp l640_test.cpp
	g++ -std=c++11 -Wall -Werror commands.cpp constants.cpp config.cpp driver.cpp support.cpp l640_test.cpp motor.cpp -o l640_test -lmraa
